keys:
  - &admin_haylin age1f2us8736c0sq54uvks0xtcmgxxy92t0yfdkh8hd775uhtp6xu3vshvfg03
  - &server_bella age1s95s5n2zuz24frnc0k6986aw5k224sc0g5wpkycdlhm3e9qsl3ysz8nnry
  - &server_maya age1cst58rc2w20fc8r770dtg3e5vtjkd4mgeyt5c4hey4n0lwfgxqdqchtvd7
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_haylin
          - *server_bella
          - *server_maya
  - path_regex: secrets/bella/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_haylin
          - *server_bella
