name: Deploy to Infrastructure
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H zoe.infra.hayl.in >> ~/.ssh/known_hosts
          ssh-keyscan -H athena.infra.hayl.in >> ~/.ssh/known_hosts
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run Colmena
        run: |
          nix-shell -p colmena --run "colmena apply --parallel 0 --build-on-target --on=zoe,athena"
